### PR TITLE
Root

### PR DESCRIPTION
**Pull request by erickfernando2**
Root

### CODE REVIEW

**Comment by erickfernando2** [comment]
https://github.com/mistersmee/android_device_motorola_cebu/pull/2#issue-691926683

**Review by erickfernando2 — COMMENTED** [review]
> @erickfernando2 @ #https://github.com/mistersmee/android_device_motorola_cebu/pull/2#issue-691926683

**Comment by mistersmee** [comment]
It's great that you noticed that this repo was behind a few commits than the fork over on the TeamWin organization.

However, as you can see, I was the one who made those commits in the first place, so I already knew it was behind. I was going to push them to this repo eventually.

Also as a friendly tip, try to be a little more descriptive than just writing "Root" as the title of the PR, and as the first comment, and then linking to that comment two more times.

**Comment by mistersmee** [comment]
Done.

**Pull request closed without merging**
